GET http://localhost:3000/

###
GET http://localhost:3000/home

###
GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "title": "Segunda Rota", 
  "startPosition": { "lat": -23.8129, "lng": -46.1143 },
  "endPosition": { "lat": -23.90, "lng": -46.47 }
}